
services:
  _defaults:
    autowire: true
    public: false

  Oksydan\IsImageslider\Domain\ImageSlider\CommandHandler\CreateImageSliderHandlerInterface:
    alias: Oksydan\IsImageslider\Domain\ImageSlider\CommandHandler\CreateImageSliderHandler

  Oksydan\IsImageslider\Domain\ImageSlider\CommandHandler\CreateImageSliderHandler:
    tags:
      - name: tactician.handler
        command: Oksydan\IsImageslider\Domain\ImageSlider\Command\CreateImageSliderCommand


  Oksydan\IsImageslider\Domain\ImageSlider\CommandHandler\EditImageSliderHandlerInterface:
    alias: Oksydan\IsImageslider\Domain\ImageSlider\CommandHandler\EditImageSliderHandler

  Oksydan\IsImageslider\Domain\ImageSlider\CommandHandler\EditImageSliderHandler:
    tags:
      - name: tactician.handler
        command: Oksydan\IsImageslider\Domain\ImageSlider\Command\EditImageSliderCommand
