services:
  Oksydan\IsImageslider\Form\DataTransformer\Shop\ShopChoiceModelDataTransformer:
    class: 'Oksydan\IsImageslider\Form\DataTransformer\Shop\ShopChoiceModelDataTransformer'
    autowire: false
    arguments:
      - '@prestashop.core.admin.shop.repository'

  Oksydan\IsImageslider\Form\EventListener\ImagesliderFormSubscriber:
    class: 'Oksydan\IsImageslider\Form\EventListener\ImagesliderFormSubscriber'
    autowire: false
    arguments:
      - '@prestashop.core.admin.shop.repository'

  Oksydan\IsImageslider\Form\DataTransformer\Lang\LangModeDataTransformer:
    class: 'Oksydan\IsImageslider\Form\DataTransformer\Lang\LangModeDataTransformer'
    autowire: false
    arguments:
      - '@prestashop.core.admin.lang.repository'

  Oksydan\IsImageslider\Form\Type\Shop\ShopAssociationChoiceTreeType:
    class: 'Oksydan\IsImageslider\Form\Type\Shop\ShopAssociationChoiceTreeType'
    autowire: false
    arguments:
      $shopTreeChoicesProvider: '@prestashop.adapter.form.choice_provider.shop_tree_choice_provider'
      $shopChoiceModelDataTransformer: '@Oksydan\IsImageslider\Form\DataTransformer\Shop\ShopChoiceModelDataTransformer'
    tags:
      - { name: form.type }

  oksydan.is_imageslider.image_slider.configuration:
    class: 'Oksydan\IsImageslider\Form\DataConfiguration\ImageSliderDataConfiguration'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.shop.context'
      - '@prestashop.adapter.multistore_feature'
