services:

  oksydan.is_imageslider.grid.definition.factory.image_sliders:
    class: 'Oksydan\IsImageslider\Grid\Definition\Factory\ImageSliderGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  oksydan.is_imageslider.grid.query.image_slider_query_builder:
    class: 'Oksydan\IsImageslider\Grid\Query\ImageSliderQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.adapter.shop.context'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"

  oksydan.is_imageslider.grid.image_slider_grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@oksydan.is_imageslider.grid.definition.factory.image_sliders'
      - '@oksydan.is_imageslider.grid.data.factory.image_slider_decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'


  oksydan.is_imageslider.grid.data.factory.image_slider_data_factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@oksydan.is_imageslider.grid.query.image_slider_query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'is_imageslider'


  oksydan.is_imageslider.grid.data.factory.image_slider_decorator:
    class: 'Oksydan\IsImageslider\Grid\Data\Factory\ImageSliderGridDataFactory'
    arguments:
      - '@oksydan.is_imageslider.grid.data.factory.image_slider_data_factory'
      - '@oksydan.is_imageslider.provider.image_provider'

  oksydan.is_imageslider.grid.position_definition:
    class: PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition
    arguments:
      - 'image_slider'
      - 'id_slide'
      - 'position'
