services:
  oksydan.is_imageslider.grid.image_slider_grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@Oksydan\IsImageslider\Grid\Definition\Factory\ImageSliderGridDefinitionFactory'
      - '@oksydan.is_imageslider.grid.data.factory.image_slider_decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  oksydan.is_imageslider.grid.data.factory.image_slider_data_factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@Oksydan\IsImageslider\Grid\Query\ImageSliderQueryBuilder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'is_imageslider'

  oksydan.is_imageslider.grid.data.factory.image_slider_decorator:
    class: 'Oksydan\IsImageslider\Grid\Data\Factory\ImageSliderGridDataFactory'
    arguments:
      - '@oksydan.is_imageslider.grid.data.factory.image_slider_data_factory'
      - '@Oksydan\IsImageslider\Provider\ImageProvider'
