imports:
  - { resource: ../common.yml }
  - { resource: ./grid.yml }
  - { resource: ./form.yml }


services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      $module: '@oksydan.is_imageslider.module'
      $context: '@oksydan.is_imageslider.context'
      $locales: '@=service("prestashop.adapter.legacy.context").getLanguages()'
      $availableLocales: "@=service('prestashop.adapter.legacy.context').getAvailableLanguages()"
      $saveFormLocaleChoice: "@=service('prestashop.adapter.legacy.configuration').getBoolean('PS_BO_ALLOW_EMPLOYEE_FORM_LANG')"
      $defaultFormLanguageId: "@=service('prestashop.adapter.legacy.context').getContext().cookie.employee_form_lang"
      $defaultShopLanguageId: "@=service('prestashop.adapter.legacy.configuration').getInt('PS_LANG_DEFAULT')"
      $shopContext: '@prestashop.adapter.shop.context'
      $multistoreFeature: '@prestashop.adapter.multistore_feature'
      $langRepository: '@prestashop.core.admin.lang.repository'
      $placeholderImage: '%is_imageslider_placeholder_img%'
      $imageSliderDataFactory: '@oksydan.is_imageslider.grid.data.factory.image_slider_decorator'
      $dbPrefix: '%database_prefix%'
      $imagesUri: '%is_imageslider_images_uri%'
      $imagesDir: '%is_imageslider_images_directory%'

  Oksydan\IsImageslider\:
    resource: '../../src/*'
    exclude:
      - '../../src/{Controller}'
      - '../../src/index.php'
      - '../../src/*/index.php'
      - '../../src/**/index.php'

  Oksydan\IsImageslider\Controller\ImagesliderController:
    class: Oksydan\IsImageslider\Controller\ImagesliderController
    arguments:
      $imagsliderGridFactory: '@oksydan.is_imageslider.grid.image_slider_grid_factory'
      $imagesliderConfigurationFormHandler: '@oksydan.is_imageslider.image_slider_configuration.form_handler'
      $imagesliderFormBuilder: '@oksydan.is_imageslider.form.identifiable_object.builder.image_slider_form_builder'
      $imagesliderFormHandler: '@oksydan.is_imageslider.form.identifiable_object.handler.image_slider_form_handler'
      $gridPresenter: '@prestashop.core.grid.presenter.grid_presenter'

