imports:
  - { resource: ../common.yml }
  - { resource: ./grid.yml }
  - { resource: ./form.yml }
  - { resource: ./command.yml }

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      $module: '@oksydan.is_imageslider.module'
      $context: '@oksydan.is_imageslider.context'
      $locales: '@=service("prestashop.adapter.legacy.context").getLanguages()'
      $availableLocales: "@=service('prestashop.adapter.legacy.context').getAvailableLanguages()"
      $saveFormLocaleChoice: "@=service('prestashop.adapter.legacy.configuration').getBoolean('PS_BO_ALLOW_EMPLOYEE_FORM_LANG')"
      $defaultFormLanguageId: "@=service('prestashop.adapter.legacy.context').getContext().cookie.employee_form_lang"
      $defaultShopLanguageId: "@=service('prestashop.adapter.legacy.configuration').getInt('PS_LANG_DEFAULT')"
      $shopContext: '@prestashop.adapter.shop.context'
      $multistoreFeature: '@prestashop.adapter.multistore_feature'
      $langRepository: '@prestashop.core.admin.lang.repository'
      $placeholderImage: '%is_imageslider_placeholder_img%'
      $imageSliderDataFactory: '@oksydan.is_imageslider.grid.data.factory.image_slider_decorator'
      $dbPrefix: '%database_prefix%'
      $imagesUri: '%is_imageslider_images_uri%'
      $imagesDir: '%is_imageslider_images_directory%'

  Oksydan\IsImageslider\:
    resource: '../../src/*'
    exclude:
      - '../../src/{Controller,Falconize,Domain}'
      - '../../src/Form/DataTransformer'
      - '../../src/Form/EventListener'
      - '../../src/Form/Type/Shop'
      - '../../src/index.php'
      - '../../src/*/index.php'
      - '../../src/**/index.php'

  Oksydan\IsImageslider\Controller\Admin\ImagesliderController:
    class: Oksydan\IsImageslider\Controller\Admin\ImagesliderController
    arguments:
      $imagsliderGridFactory: '@oksydan.is_imageslider.grid.image_slider_grid_factory'
      $gridPresenter: '@prestashop.core.grid.presenter.grid_presenter'

  Oksydan\IsImageslider\Adapter\CommandBusInterface: '@Oksydan\IsImageslider\Adapter\CommandBus'
  Oksydan\IsImageslider\Adapter\CommandBus:
    class: Oksydan\IsImageslider\Adapter\CommandBus
    autowire: false
    public: false
    arguments:
      - '@prestashop.core.command_bus'

