database_tables:
  image_slider:
    columns:
      - name: id_slide
        type: integer
        length: 11
        notnull: true
        autoincrement: true
      - name: active
        type: boolean
        notnull: true
      - name: position
        type: integer
        length: 11
        notnull: true
      - name: display_from
        type: datetime
        notnull: false
        default: null
      - name: display_to
        type: datetime
        notnull: false
        default: null
    primary:
      - id_slide

