database_tables:
  image_slider_lang:
    columns:
      - name: id_slide
        type: integer
        length: 11
        notnull: true
      - name: id_lang
        type: integer
        length: 11
        notnull: true
      - name: title
        type: string
        length: 255
        notnull: true
      - name: legend
        type: string
        length: 255
        notnull: false
      - name: image
        type: integer
        length: 11
        notnull: false
      - name: image_mobile
        type: integer
        length: 11
        notnull: false
      - name: url
        type: string
        length: 255
        notnull: true
      - name: description
        type: text
        notnull: false
    primary:
      - id_slide
      - id_lang

    constraint_keys:
      - name: is_imageslider_constraint_lang
        foreign_table: lang
        update: NO ACTION
        delete: CASCADE
        local_columns:
          - id_lang
        foreign_columns:
          - id_lang

#      - name: is_imageslider_constraint_image_slider_image_lang
#        foreign_table: image_slider_image
#        update: NO ACTION
#        delete: CASCADE
#        local_columns:
#          - image
#        foreign_columns:
#          - id_image
#
#      - name: is_imageslider_constraint_image_slider_image_mobile_lang
#        foreign_table: image_slider_image
#        update: NO ACTION
#        delete: CASCADE
#        local_columns:
#          - image_mobile
#        foreign_columns:
#          - id_image
